"use client";
import "./globals.css";
import Navbar from "../components/Navbar";
import { LanguageProvider, useLanguage } from "../context/LanguageContext";

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

function AppContent({ children }) {
  const { language } = useLanguage();
  return (
    <html lang={language} dir={language === "fa" ? "rtl" : "ltr"}>
      <body className="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white">
        <Navbar />
        <main className="max-w-3xl mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}

export default function RootLayout({ children }) {
  return (
    <LanguageProvider>
      <AppContent>{children}</AppContent>
    </LanguageProvider>
  );
}
